# Generated by Django 5.0 on 2026-04-17 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_key', models.CharField(help_text="Identifiant unique dans l'histoire, ex: scene_01, scene_kidnap", max_length=100, verbose_name='Clé de scène')),
                ('narrative', models.TextField(verbose_name='Texte narratif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='scenes/', verbose_name="Image d'ambiance")),
                ('music_file', models.CharField(default='calm_ambient.mp3', help_text='Nom du fichier dans static/music/, ex: calm_ambient.mp3', max_length=100, verbose_name='Fichier musical')),
                ('music_transition', models.CharField(choices=[('fade', 'Fondu (fade)'), ('instant', 'Instantanée (choc dramatique)'), ('continuous', 'Continue (même ambiance)')], default='fade', max_length=20, verbose_name='Transition musicale')),
                ('is_starting_scene', models.BooleanField(default=False, verbose_name='Scène de départ')),
                ('is_ending', models.BooleanField(default=False, verbose_name='Scène de fin')),
                ('ending_type', models.CharField(blank=True, choices=[('good', 'Bonne fin'), ('bad', 'Mauvaise fin'), ('neutral', 'Fin neutre')], max_length=10, null=True, verbose_name='Type de fin')),
            ],
            options={
                'verbose_name': 'Scène',
                'verbose_name_plural': 'Scènes',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(verbose_name='Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Image de couverture')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publiée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
            ],
            options={
                'verbose_name': 'Histoire',
                'verbose_name_plural': 'Histoires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Texte du choix')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('next_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_choices', to='stories.scene', verbose_name='Scène suivante')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='stories.scene', verbose_name='Scène')),
            ],
            options={
                'verbose_name': 'Choix',
                'verbose_name_plural': 'Choix',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='scene',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='stories.story', verbose_name='Histoire'),
        ),
        migrations.AlterUniqueTogether(
            name='scene',
            unique_together={('story', 'scene_key')},
        ),
    ]
