# Generated by Django 5.0 on 2026-04-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='audio_narration',
            field=models.FileField(blank=True, help_text="Fichier audio lu par le narrateur — mp3/ogg/wav, uploadé via l'admin", null=True, upload_to='narrations/', verbose_name='Narration audio'),
        ),
    ]
