# Generated by Django 6.1 on 2026-09-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_scene_music_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='image_auto_generate',
            field=models.BooleanField(default=True, help_text="Génère l'image de fond avec l'IA à l'enregistrement, tant qu'aucune image n'a été uploadée à la main. Décochez pour gérer le visuel vous-même.", verbose_name='Illustrer automatiquement'),
        ),
        migrations.AddField(
            model_name='scene',
            name='image_is_generated',
            field=models.BooleanField(default=False, editable=False, verbose_name="Image générée par l'IA"),
        ),
        migrations.AddField(
            model_name='scene',
            name='image_prompt',
            field=models.TextField(blank=True, default='', help_text="Description envoyée au générateur d'images. Laissez vide : Gemini l'écrit automatiquement à partir du texte narratif. Si vous le modifiez, l'image est refaite au prochain enregistrement.", verbose_name='Prompt visuel (IA)'),
        ),
        migrations.AddField(
            model_name='scene',
            name='image_source_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=40, verbose_name='Empreinte du texte illustré'),
        ),
    ]
