# Generated by Django 5.0 on 2026-04-17 08:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True, verbose_name='Visité le')),
            ],
            options={
                'verbose_name': 'Historique de scène',
                'verbose_name_plural': 'Historiques de scènes',
                'ordering': ['visited_at'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Démarré le')),
                ('last_played', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Terminée')),
                ('platform', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile (Flutter)')], default='web', max_length=10, verbose_name='Plateforme')),
                ('current_scene', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_sessions', to='stories.scene', verbose_name='Scène actuelle')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='stories.story', verbose_name='Histoire')),
            ],
            options={
                'verbose_name': 'Session de jeu',
                'verbose_name_plural': 'Sessions de jeu',
                'ordering': ['-last_played'],
            },
        ),
    ]
