# Generated by Django 5.0 on 2026-04-17 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_sessions', '0001_initial'),
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Joueur'),
        ),
        migrations.AddField(
            model_name='sessionhistory',
            name='choice_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='stories.choice', verbose_name='Choix effectué'),
        ),
        migrations.AddField(
            model_name='sessionhistory',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='stories.scene', verbose_name='Scène visitée'),
        ),
        migrations.AddField(
            model_name='sessionhistory',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='game_sessions.gamesession', verbose_name='Session'),
        ),
        migrations.AlterUniqueTogether(
            name='gamesession',
            unique_together={('user', 'story')},
        ),
    ]
